version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - MONGO_URI=mongodb://mongo_user:mongo_password@mongo:27017
      - DB_NAME=db_books
    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - server
    environment:
      - GRPC_SERVER=server:50051

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: